<?php

	$cities = array(
		'Atlanta' => array('Miami','Washington','Chicago'),
		'Algiers' => array('Cairo','Madrid','Paris','Istanbul'),
		'Baghdad' => array('Karachi','Riyadh','Istanbul','Cairo','Tehran'),
		'Bangkok' => array('Jakarta','Chennai','Kolkata','Ho Chi Minh City','Hong Kong'),
		'Beijing' => array('Shanghai','Seoul'),
		'Bogota' => array('Mexico City','Lima','Miami','Sao Paulo', 'Buenos Aires'),
		'Buenos Aires' => array('Sao Paulo','Bogota'),
		'Cairo' => array('Riyadh','Algiers','Baghdad','Istanbul','Khartoum'),
		'Chennai' => array('Jakarta','Bangkok','Mumbai','Delhi','Kolkata'),
		'Delhi' => array('Kolkata','Karachi','Tehran','Mumbai','Chennai'),
		'Chicago' => array('Atlanta','San Francisco','Los Angeles','Mexico City','Montreal'),
		'Essen' => array('London','Paris','St Petersburg','Milan'),
		'Ho Chi Minh City' => array('Manila','Jakarta','Bangkok','Hong Kong'),
		'Hong Kong' => array('Ho Chi Minh City','Manila','Bangkok','Taipei','Shanghai','Kolkata'),
		'Istanbul' => array('Baghdad','Cairo','Algiers','Milan','St Petersburg','Moscow', 'Baghdad'),
		'Jakarta' => array('Ho Chi Minh City','Bangkok','Sydney','Chennai'),
		'Johannesburg' => array('Kinshasa','Khartoum'),
		'Karachi' => array('Delhi','Tehran','Baghdad','Riyadh','Mumbai'),
		'Khartoum' => array('Kinshasa','Johannesburg','Cairo','Lagos'),
		'Kinshasa' => array('Lagos','Khartoum','Johannesburg'),
		'Kolkata' => array('Hong Kong','Bangkok','Chennai','Delhi'),
		'Lagos' => array('Kinshasa','Khartoum','Sao Paulo'),
		'Lima' => array('Santiago','Bogota','Mexico City'),
		'London' => array('Essen','Paris','Madrid','New York'),
		'Los Angeles' => array('Chicago','San Francisco','Mexico City','Sydney'),
		'Madrid' => array('Sao Paulo','Paris','London','Algiers','New York'),
		'Manila' => array('Sydney','Taipei','Hong Kong','Ho Chi Minh City','San Francisco'),
		'Mexico City' => array('Miami','Los Angeles','Bogota','Lima','Chicago'),
		'Miami' => array('Washington','Bogota','Mexico City','Atlanta'),
		'Milan' => array('Paris','Essen','Istanbul',''),
		'Montreal' => array('Washington','Chicago','New York'),
		'Moscow' => array('St Petersburg','Tehran','Istanbul'),
		'Mumbai' => array('Chennai','Karachi','Delhi',''),
		'New York' => array('London','Madrid','Washington','Montreal'),
		'Osaka' => array('Tokyo','Taipei'),
		'Paris' => array('Madrid','Algiers','London','Essen','Milan'),
		'Riyadh' => array('Karachi','Baghdad','Cairo'),
		'San Francisco' => array('Chicago','Tokyo','Los Angeles','Manila'),
		'Santiago' => array('Lima'),
		'Sao Paulo' => array('Madrid','Lagos','Buenos Aires','Bogota'),
		'Seoul' => array('Beijing','Shanghai','Tokyo'),
		'Shanghai' => array('Beijing','Taipei','Seoul','Tokyo','Hong Kong'),
		'St Petersburg' => array('Essen','Moscow','Istanbul'),
		'Sydney' => array('Manila','Jakarta','Los Angeles'),
		'Taipei' => array('Osaka','Manila','Hong Kong','Shanghai'),
		'Tehran' => array('Kolkata','Moscow','Karachi','Baghdad'),
		'Tokyo' => array('Seoul','Osaka','Shanghai','San Francisco'),
		'Washington' => array('New York','Miami','Atlanta','Montreal')

		 );

?>